server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope: [openid, profile, email]
        provider:
          google:
            issuer-uri: https://accounts.google.com

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  oauth:
    enabled: ${APP_OAUTH_ENABLED:false}
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
