spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sportsbook   # use 5433 if you mapped 5433
    username: sb
    password: password123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
