server:
  # Heroku provides PORT; default to 8080 locally
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

app:
  oauth:
    enabled: ${APP_OAUTH_ENABLED:false}
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

spring:
  datasource:
    # Prefer SPRING_DATASOURCE_URL if present, otherwise fall back to JawsDB URL
    url: ${SPRING_DATASOURCE_URL:${JAWSDB_URL}}
  jpa:
    show-sql: true
    hibernate:
      # keep schema managed by Flyway (or by your SQL), not by Hibernate
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  security:
    oauth2:
      client: {}  # placeholder while OAuth is unfinished

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
