# application.yml
# Heroku + JawsDB MariaDB + Spring Boot 3

spring:
  datasource:
    # Heroku env vars: SPRING_DATASOURCE_URL/USERNAME/PASSWORD are set in Config Vars.
    # Fallback to JDBC_DATABASE_URL if present.
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:${JDBC_DATABASE_URL:}}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      # Keep this small for JawsDB free/shared plans
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 25000
      idle-timeout: 300000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none           # Flyway manages schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: true
    locations: classpath:db/migration  # V1__init.sql, V2__seed.sql here
    clean-disabled: true               # don't wipe the DB on startup
#NEW OAUTH CHANGES HERE
    security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23livgqylxL6y8WCnX 
            client-secret: 93a0c79c3c0ec5f66bf956bf7fecdc39a8bf5770
            scope: user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id


  # Global CORS (fixes "allowCredentials + *" error)
  mvc:
    cors:
      mappings:
        "[/**]":
          allowed-origin-patterns:
            - "http://localhost:3000"
            - "http://localhost:5173"
            - "https://*.vercel.app"
            - "https://*.netlify.app"
            - "https://<your-frontend-domain>"  # replace with your real frontend origin if needed
          allowed-methods: [GET, POST, PUT, DELETE, OPTIONS]
          allowed-headers: "*"
          allow-credentials: true
          max-age: 3600

server:
  forward-headers-strategy: native

management:
  endpoints:
    web:
      exposure:
        include: health,info
