ALTER TABLE bets
  MODIFY created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

ALTER TABLE bets
  MODIFY updated_at DATETIME(6) NULL DEFAULT NULL;

ALTER TABLE bets
  MODIFY status VARCHAR(32) NOT NULL DEFAULT 'PENDING';
