spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sportsbook   # use 5433 if you mapped 5433
    username: sb
    password: password123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23livgqylxL6y8WCnX 
            client-secret: 93a0c79c3c0ec5f66bf956bf7fecdc39a8bf5770
            scope: user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

app:
  oauth:
    enabled: ${APP_OAUTH_ENABLED:false}
