-- Users
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL UNIQUE,
  display_name VARCHAR(255),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Events
CREATE TABLE IF NOT EXISTS events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  league VARCHAR(64) NOT NULL,
  home_team VARCHAR(128) NOT NULL,
  away_team VARCHAR(128) NOT NULL,
  start_time DATETIME(6) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'SCHEDULED',
  result VARCHAR(32) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Markets (e.g., MONEYLINE)
CREATE TABLE IF NOT EXISTS markets (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  event_id BIGINT NOT NULL,
  type VARCHAR(64) NOT NULL,
  CONSTRAINT fk_markets_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Odds for a market (HOME/AWAY)
CREATE TABLE IF NOT EXISTS odds (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  market_id BIGINT NOT NULL,
  selection VARCHAR(32) NOT NULL, -- HOME or AWAY
  american INT NOT NULL,
  decimal DECIMAL(6,2) NOT NULL,
  CONSTRAINT fk_odds_market FOREIGN KEY (market_id) REFERENCES markets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Bets
CREATE TABLE IF NOT EXISTS bets (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  event_id BIGINT NOT NULL,
  user_id BIGINT NULL, -- hook up auth later
  selection VARCHAR(120) NOT NULL,    -- e.g., 'HOME' or 'AWAY'
  odds_decimal DECIMAL(8,4) NOT NULL, -- e.g., 1.9100
  stake DECIMAL(10,2) NOT NULL,
  bettor_ref VARCHAR(255) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NULL DEFAULT NULL,
  CONSTRAINT fk_bets_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
