CREATE TABLE IF NOT EXISTS bets (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  event_id BIGINT NOT NULL,
  user_id BIGINT NULL,
  amount DECIMAL(18,2) NOT NULL,
  selection VARCHAR(16) NOT NULL,
  odds INT NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE bets ADD COLUMN IF NOT EXISTS event_id   BIGINT NOT NULL;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS user_id    BIGINT NULL;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS amount     DECIMAL(18,2) NOT NULL;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS selection  VARCHAR(16) NOT NULL;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS odds       INT NOT NULL;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS status     VARCHAR(16) NOT NULL;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_bets_event_id ON bets (event_id);
